version: '3.8'
services:
  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/server
  admin:
    build: ./admin
    ports:
      - "3000:3000"
    depends_on:
        # Starts up the server service before starting up the react service
      - server
    volumes:
      - ./admin/src:/app/src
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017